/***********************************************************************/
/*                                                                     */
/*  FILE        :typedefine.h                                          */
/*  DATE        :Tue, Jun 04, 2013                                     */
/*  DESCRIPTION :define scalar types.                                  */
/*  CPU GROUP   :Other                                                 */
/*                                                                     */
/*  This file is generated by Renesas Project Generator (Ver.4.18).    */
/*  NOTE:THIS IS A TYPICAL EXAMPLE.                                    */
/***********************************************************************/

/*************************************************
* COMPILER for R8C/Tiny
*
* Copyright (C) 2004 (2010) Renesas Electronics Corporation.
* and Renesas Solutions Corporation. All rights reserved.
*
* typedef for startup
*
* $Date: 2005/11/01 04:31:54 $
* $Revision: 1.4 $
************************************************/
#ifndef __TYPEDEF__
typedef signed char _SBYTE;
typedef unsigned char _UBYTE;
typedef signed short _SWORD;
typedef unsigned short _UWORD;
typedef signed int _SINT;
typedef unsigned int _UINT;
typedef signed long _SDWORD;
typedef unsigned long _UDWORD;
typedef signed long long _SQDWORD;
typedef unsigned long long _UQDWORD;
#endif
#define __TYPEDEF__
