<html>
<meta http-equiv="refresh" content="3">
<body>

<table>
    <tr>
        <td><b>Results</b></td>
    </tr>
    <tr>
        <td>Pot1:</td>
        <td>%02</td>
    </tr>
    <tr>
        <td>Pot2:</td>
        <td>%03</td>
    </tr>
</table>

<table cellpadding="3">
    <tr>
        <td>Switch:</td>
        <td>%04</td>
    </tr>
    <tr>
        <td>LEDs:</td>
        <td>D6=%01</td>
        <td>D5=%00</td>
    </tr>
</table>
</body>
</html>
