/* definitions generated by preprocessor, copy into defines.h */		
#ifndef	PPINC	
#define	_ATMEGA163	// device select: _ATMEGAxxxx
#define	_B512	// boot size select: _Bxxx (words)
#include	"iom163.h"	

/* definitions for UART control */		
#define	BAUD_RATE_LOW_REG	UBRRLO
#define	UART_CONTROL_REG	UCSRB
#define	ENABLE_TRANSMITTER_BIT	TXEN
#define	ENABLE_RECEIVER_BIT	RXEN
#define	UART_STATUS_REG	UCSRA
#define	TRANSMIT_COMPLETE_BIT	TXC
#define	RECEIVE_COMPLETE_BIT	RXC
#define	UART_DATA_REG	UDR

/* definitions for SPM control */		
#define	LOAD_SPM_CONTROL_REGISTER_MACRO	OUT SPMCR, R18
#define	GET_SPM_CONTROL_REGISTER_MACRO	IN R18, SPMCR
#define	REENABLE_RWW_BIT	ASRE
//#define	LARGE_MEMORY	
#define	PAGESIZE	128
#define	APP_END	15360

/* definitions for AVRProg communication */		
#define	PARTCODE	0x66
#define	SIGNATURE_BYTE_1	0x1E
#define	SIGNATURE_BYTE_2	0x94
#define	SIGNATURE_BYTE_3	0x02

/* define pin for enter-self-prog-mode */		
#define	PROGPORT	PORTD
#define	PROGPIN	PIND
#define	PROGCTRL	(1<<PD4)
#define	PROGMODE	!(PROGPIN & PROGCTRL)

/* indicate preprocessor result included */		
#define	PPINC	
#endif		
