<html><meta http-equiv="refresh" content="4">
<head><title>Web ver Status</title>
<STYLE TYPE="text/css">
H3
   {
   font-family:sans-serif;
   color:red;
   font-size:50pt;
   }

</STYLE>
</head>
<body>

<font face=helvetica>
<h2><center> System Status  </h2>
<table boarder="4" cellspacing="5" cellpadding="10" bgcolor="#000000">

<tr>
       <td><h3> %03 <sup>o</sup>C </h3></td>
</tr>
</table>Heater = %01
<br>Fan = %00
</body></html>
