foldersTree = gFld("<b>Procyon AVRlib</b>", "", "")
     insDoc(foldersTree, gLnk("Procyon AVRlib", "", "main.html"))
aux1 = insFld(foldersTree, gFld("File List", "", "files.html"))
       insDoc(aux1, gLnk("a2d.c", "", "a2d_8c.html"))
       insDoc(aux1, gLnk("a2d.h", "", "a2d_8h.html"))
       insDoc(aux1, gLnk("ads7828.c", "", "ads7828_8c.html"))
       insDoc(aux1, gLnk("ads7828.h", "", "ads7828_8h.html"))
       insDoc(aux1, gLnk("ata.c", "", "ata_8c.html"))
       insDoc(aux1, gLnk("ata.h", "", "ata_8h.html"))
       insDoc(aux1, gLnk("avrlibdefs.h", "", "avrlibdefs_8h.html"))
       insDoc(aux1, gLnk("avrlibtypes.h", "", "avrlibtypes_8h.html"))
       insDoc(aux1, gLnk("bitbuf.c", "", "bitbuf_8c.html"))
       insDoc(aux1, gLnk("bitbuf.h", "", "bitbuf_8h.html"))
       insDoc(aux1, gLnk("buffer.c", "", "buffer_8c.html"))
       insDoc(aux1, gLnk("buffer.h", "", "buffer_8h.html"))
       insDoc(aux1, gLnk("cmdline.c", "", "cmdline_8c.html"))
       insDoc(aux1, gLnk("cmdline.h", "", "cmdline_8h.html"))
       insDoc(aux1, gLnk("debug.c", "", "debug_8c.html"))
       insDoc(aux1, gLnk("debug.h", "", "debug_8h.html"))
       insDoc(aux1, gLnk("ds1631.c", "", "ds1631_8c.html"))
       insDoc(aux1, gLnk("ds1631.h", "", "ds1631_8h.html"))
       insDoc(aux1, gLnk("encoder.c", "", "encoder_8c.html"))
       insDoc(aux1, gLnk("encoder.h", "", "encoder_8h.html"))
       insDoc(aux1, gLnk("fat.c", "", "fat_8c.html"))
       insDoc(aux1, gLnk("fat.h", "", "fat_8h.html"))
       insDoc(aux1, gLnk("fixedpt.c", "", "fixedpt_8c.html"))
       insDoc(aux1, gLnk("fixedpt.h", "", "fixedpt_8h.html"))
       insDoc(aux1, gLnk("font5x7.h", "", "font5x7_8h.html"))
       insDoc(aux1, gLnk("fontgr.h", "", "fontgr_8h.html"))
       insDoc(aux1, gLnk("glcd.c", "", "glcd_8c.html"))
       insDoc(aux1, gLnk("glcd.h", "", "glcd_8h.html"))
       insDoc(aux1, gLnk("gps.c", "", "gps_8c.html"))
       insDoc(aux1, gLnk("gps.h", "", "gps_8h.html"))
       insDoc(aux1, gLnk("i2c.c", "", "i2c_8c.html"))
       insDoc(aux1, gLnk("i2c.h", "", "i2c_8h.html"))
       insDoc(aux1, gLnk("i2ceeprom.c", "", "i2ceeprom_8c.html"))
       insDoc(aux1, gLnk("i2ceeprom.h", "", "i2ceeprom_8h.html"))
       insDoc(aux1, gLnk("i2csw.c", "", "i2csw_8c.html"))
       insDoc(aux1, gLnk("i2csw.h", "", "i2csw_8h.html"))
       insDoc(aux1, gLnk("ks0108.c", "", "ks0108_8c.html"))
       insDoc(aux1, gLnk("ks0108.h", "", "ks0108_8h.html"))
       insDoc(aux1, gLnk("lcd.c", "", "lcd_8c.html"))
       insDoc(aux1, gLnk("lcd.h", "", "lcd_8h.html"))
       insDoc(aux1, gLnk("nmea.c", "", "nmea_8c.html"))
       insDoc(aux1, gLnk("nmea.h", "", "nmea_8h.html"))
       insDoc(aux1, gLnk("port128.h", "", "port128_8h.html"))
       insDoc(aux1, gLnk("pulse.c", "", "pulse_8c.html"))
       insDoc(aux1, gLnk("pulse.h", "", "pulse_8h.html"))
       insDoc(aux1, gLnk("pwmsw.c", "", "pwmsw_8c.html"))
       insDoc(aux1, gLnk("pwmsw.h", "", "pwmsw_8h.html"))
       insDoc(aux1, gLnk("rprintf.c", "", "rprintf_8c.html"))
       insDoc(aux1, gLnk("rprintf.h", "", "rprintf_8h.html"))
       insDoc(aux1, gLnk("rprintfconf.h", "", "rprintfconf_8h.html"))
       insDoc(aux1, gLnk("rtc.c", "", "rtc_8c.html"))
       insDoc(aux1, gLnk("rtc.h", "", "rtc_8h.html"))
       insDoc(aux1, gLnk("servo.c", "", "servo_8c.html"))
       insDoc(aux1, gLnk("servo.h", "", "servo_8h.html"))
       insDoc(aux1, gLnk("spi.c", "", "spi_8c.html"))
       insDoc(aux1, gLnk("spi.h", "", "spi_8h.html"))
       insDoc(aux1, gLnk("sramsw.c", "", "sramsw_8c.html"))
       insDoc(aux1, gLnk("sramsw.h", "", "sramsw_8h.html"))
       insDoc(aux1, gLnk("sta013.c", "", "sta013_8c.html"))
       insDoc(aux1, gLnk("sta013.h", "", "sta013_8h.html"))
       insDoc(aux1, gLnk("stxetx.c", "", "stxetx_8c.html"))
       insDoc(aux1, gLnk("stxetx.h", "", "stxetx_8h.html"))
       insDoc(aux1, gLnk("timer.c", "", "timer_8c.html"))
       insDoc(aux1, gLnk("timer.h", "", "timer_8h.html"))
       insDoc(aux1, gLnk("timer128.c", "", "timer128_8c.html"))
       insDoc(aux1, gLnk("timer128.h", "", "timer128_8h.html"))
       insDoc(aux1, gLnk("tsip.c", "", "tsip_8c.html"))
       insDoc(aux1, gLnk("tsip.h", "", "tsip_8h.html"))
       insDoc(aux1, gLnk("uart.c", "", "uart_8c.html"))
       insDoc(aux1, gLnk("uart.h", "", "uart_8h.html"))
       insDoc(aux1, gLnk("uart2.c", "", "uart2_8c.html"))
       insDoc(aux1, gLnk("uart2.h", "", "uart2_8h.html"))
       insDoc(aux1, gLnk("uartsw.c", "", "uartsw_8c.html"))
       insDoc(aux1, gLnk("uartsw.h", "", "uartsw_8h.html"))
       insDoc(aux1, gLnk("vt100.c", "", "vt100_8c.html"))
       insDoc(aux1, gLnk("vt100.h", "", "vt100_8h.html"))
       insDoc(aux1, gLnk("conf/ataconf.h", "", "ataconf_8h.html"))
       insDoc(aux1, gLnk("conf/cmdlineconf.h", "", "cmdlineconf_8h.html"))
       insDoc(aux1, gLnk("conf/encoderconf.h", "", "encoderconf_8h.html"))
       insDoc(aux1, gLnk("conf/fatconf.h", "", "fatconf_8h.html"))
       insDoc(aux1, gLnk("conf/global.h", "", "global_8h.html"))
       insDoc(aux1, gLnk("conf/i2cconf.h", "", "i2cconf_8h.html"))
       insDoc(aux1, gLnk("conf/i2cswconf.h", "", "i2cswconf_8h.html"))
       insDoc(aux1, gLnk("conf/ks0108conf.h", "", "ks0108conf_8h.html"))
       insDoc(aux1, gLnk("conf/lcdconf.h", "", "lcdconf_8h.html"))
       insDoc(aux1, gLnk("conf/servoconf.h", "", "servoconf_8h.html"))
       insDoc(aux1, gLnk("conf/sramswconf.h", "", "sramswconf_8h.html"))
       insDoc(aux1, gLnk("conf/sta013conf.h", "", "sta013conf_8h.html"))
       insDoc(aux1, gLnk("conf/stxetxconf.h", "", "stxetxconf_8h.html"))
aux1 = insFld(foldersTree, gFld("Data Structures", "", "annotated.html"))
       insDoc(aux1, gLnk("struct_EncoderState", "", "structstruct__EncoderState.html"))
     insDoc(foldersTree, gLnk("Data Fields", "", "functions.html"))
aux1 = insFld(foldersTree, gFld("Modules", "", "modules.html"))
       insDoc(aux1, gLnk("a2d: Analog-to-Digital Converter Functions", "", "group__a2d.html"))
       insDoc(aux1, gLnk("ads7828: TI ADS7828 I2C A/D Converter Driver", "", "group__ads7828.html"))
       insDoc(aux1, gLnk("ata: IDE/ATA Interface Driver", "", "group__ata.html"))
       insDoc(aux1, gLnk("bitbuf: Generic Bit-Buffer Structure and Function Library", "", "group__bitbuf.html"))
       insDoc(aux1, gLnk("buffer: Generic Byte-Buffer Structure and Function Library", "", "group__buffer.html"))
       insDoc(aux1, gLnk("ds1631: Dallas DS1631 Temperature Sensor Driver", "", "group__ds1631.html"))
       insDoc(aux1, gLnk("encoder: Quadrature Encoder Driver", "", "group__encoder.html"))
       insDoc(aux1, gLnk("fat: FAT16/32 File System Interface", "", "group__fat.html"))
       insDoc(aux1, gLnk("fixedpt: Fixed-Point Math Function Library", "", "group__fixedpt.html"))
       insDoc(aux1, gLnk("glcd: Graphic LCD API (application programmer's interface)", "", "group__glcd.html"))
       insDoc(aux1, gLnk("gps: GPS Positioning and Navigation Function Library", "", "group__gps.html"))
       insDoc(aux1, gLnk("i2c: I2C Serial Interface Function Library", "", "group__i2c.html"))
       insDoc(aux1, gLnk("i2ceeprom: Interface for standard I2C EEPROM memories", "", "group__i2ceeprom.html"))
       insDoc(aux1, gLnk("i2csw: Software-driven I2C Serial Interface Function Library", "", "group__i2csw.html"))
       insDoc(aux1, gLnk("ks0108: Graphic LCD Driver for HD61202/KS0108-based Displays", "", "group__ks0108.html"))
       insDoc(aux1, gLnk("lcd: Character LCD Driver for HD44780/SED1278-based displays", "", "group__lcd.html"))
       insDoc(aux1, gLnk("nmea: NMEA Packet Interface for GPS Receivers", "", "group__nmea.html"))
       insDoc(aux1, gLnk("pulse: Pulse Function Library", "", "group__pulse.html"))
       insDoc(aux1, gLnk("pwmsw: Software Interrupt-driven Multi-output PWM Function Library", "", "group__pwmsw.html"))
       insDoc(aux1, gLnk("rprintf: printf() Function Library (for general and specific data types)", "", "group__rprintf.html"))
       insDoc(aux1, gLnk("servo: Interrupt-driven RC Servo Function Library", "", "group__servo.html"))
       insDoc(aux1, gLnk("spi: SPI (Serial Peripheral Interface) Function Library", "", "group__spi.html"))
       insDoc(aux1, gLnk("sta013: STMicroelectronics STA013 MP3 Player Driver", "", "group__sta013.html"))
       insDoc(aux1, gLnk("stxetx: STX/ETX Packet Protocol Function Library", "", "group__stxetx.html"))
       insDoc(aux1, gLnk("timer: Timer Function Library", "", "group__timer.html"))
       insDoc(aux1, gLnk("timer128: Timer Function Library for the ATmega128", "", "group__timer128.html"))
       insDoc(aux1, gLnk("tsip: TSIP Packet Interface for Trimble GPS Receivers", "", "group__tsip.html"))
       insDoc(aux1, gLnk("uart: UART (serial port) Driver/Function Library", "", "group__uart.html"))
       insDoc(aux1, gLnk("uart2: Dual UART (serial port) Driver/Function Library for the Mega161 and Mega128", "", "group__uart2.html"))
       insDoc(aux1, gLnk("uartsw: Software Interrupt-driven UART Function Library", "", "group__uartsw.html"))
       insDoc(aux1, gLnk("vt100: VT100 Terminal Function Library", "", "group__vt100.html"))
     insDoc(foldersTree, gLnk("Globals", "", "globals.html"))
