#
# Copyright ARM Limited 1998-2000. All rights reserved.
# makefile for zlib
#

include environ.in

#------------------------------------------------------------
#  Build everything by calling each makefile.
#------------------------------------------------------------
all:	
	echo '*** Making zlib' ; cd Build ; $(MAKE) all

#------------------------------------------------------------
#  clean up the development tree.
#------------------------------------------------------------
clean:	
	rm -f *~ ./*/*~ ./*/*.bak
	echo '*** Cleaning zlib' ; cd Build ; $(MAKE) clean

