/*  PROGRAMABLE LOGIC ARRAY   */

#define PLABASE 	(*(volatile unsigned long *) 	0XFFFF0B00)
#define PLAELM0 	(*(volatile unsigned long *) 	0XFFFF0B00)
#define PLAELM1 	(*(volatile unsigned long *) 	0XFFFF0B04)
#define PLAELM2 	(*(volatile unsigned long *) 	0XFFFF0B08)
#define PLAELM3 	(*(volatile unsigned long *) 	0XFFFF0B0C)
#define PLAELM4 	(*(volatile unsigned long *)	0XFFFF0B10)
#define PLAELM5 	(*(volatile unsigned long *) 	0XFFFF0B14)
#define PLAELM6 	(*(volatile unsigned long *) 	0XFFFF0B18)
#define PLAELM7 	(*(volatile unsigned long *) 	0XFFFF0B1C)
#define PLAELM8 	(*(volatile unsigned long *) 	0XFFFF0B20)
#define PLAELM9 	(*(volatile unsigned long *) 	0XFFFF0B24)
#define PLAELM10 	(*(volatile unsigned long *) 	0XFFFF0B28)
#define PLAELM11 	(*(volatile unsigned long *) 	0XFFFF0B2C)
#define PLAELM12 	(*(volatile unsigned long *) 	0XFFFF0B30)
#define PLAELM13 	(*(volatile unsigned long *) 	0XFFFF0B34)
#define PLAELM14 	(*(volatile unsigned long *) 	0XFFFF0B38)
#define PLAELM15 	(*(volatile unsigned long *) 	0XFFFF0B3C)
#define PLACLK 		(*(volatile unsigned long *) 	0XFFFF0B40)
#define PLAIRQ 		(*(volatile unsigned long *) 	0XFFFF0B44)
#define PLAADC 		(*(volatile unsigned long *) 	0XFFFF0B48)
#define PLADIN 		(*(volatile unsigned long *) 	0XFFFF0B4C)
#define PLADOUT 	(*(volatile unsigned long *) 	0XFFFF0B50)
